 // 尾部
 $('#wx1').on('mouseenter',function(){
    $('.gzh1').css({
      'display':'block'
    })
  })
  $('#dy1').on('mouseenter',function(){
    $('.gzh2').css({
      'display':'block'
    })
  })
  $('#wx1').on('mouseleave',function(){
    $('.gzh1').css({
      'display':'none'
    })
  })
  $('#dy1').on('mouseleave',function(){
    $('.gzh2').css({
      'display':'none'
    })
  })